import assert from 'node:assert/strict';
import {penisuelaGalleryGameplay as definition, penisuelaGalleryHeroes as heroes} from '../src/entities/campaign-session/model/data';
import {replayGalleryEvents, createSafeLocationRestCommand, type GalleryEvent} from '../src/entities/campaign-session/model/gallerySession';
import {createGallerySessionStartedEvent, createStoredGallerySessionEnvelope, parseStoredGallerySessionEnvelope} from '../src/entities/campaign-session/model/gallerySessionJournal';
import {createOlvaRestCommand} from '../src/entities/campaign-session/model/olvaRest';
import {isCombatActionSourceAvailable, createCombatActionUsageEvent, getCombatActionResourceKey} from '../src/features/run-combat/model/combatCommands';

let serial = 0;
const ev = (input: object, commandId = `command-${++serial}`) => ({...input, id:`test-${++serial}`,commandId}) as GalleryEvent;
const seed = createGallerySessionStartedEvent({definition, heroes, existingInventory:[], eventId:'seed',commandId:'seed'});
const log: GalleryEvent[] = [seed,ev({type:'item-changed',itemId:'olva-timeout',acquired:true})];
const replay = () => replayGalleryEvents(log,definition);
for (const hero of heroes) log.push(ev({type:'manual-adjustment',label:'Урон',reason:'Тест',adjustment:{kind:'participant-stat',participantId:hero.id,field:'hp',value:0}}));
log.push(ev({type:'manual-adjustment',label:'Максимум',reason:'Тест',adjustment:{kind:'participant-stat',participantId:'linda',field:'maxHp',value:41}}));
log.push(ev({type:'manual-adjustment',label:'Без сознания',reason:'Тест',adjustment:{kind:'condition',participantId:'linda',conditionId:'downed',active:true}}));
for (const id of ['healing-pollen','buldak-noodles','ice-heart','sleep-scroll']) log.push(ev({type:'item-charge-changed',itemId:id,change:{mode:'set',value:0}}));
for (const [resourceKey,scope] of [['linda-item-healing-pollen','campaign'],['bubsilda-item-ice-heart','campaign'],['linda-ability-pitahaya-summon','campaign'],['linda-ability-magic-whisper','location']] as const) log.push(ev({type:'combat-action-used',actionId:'fixture',sourceId:'fixture',resourceKey,scope,max:3}));
const heroIds = new Set(heroes.map(hero => hero.id));
const allHeroActions = definition.combatActions.filter(action => heroIds.has(action.characterId));
for (const action of allHeroActions) {
  for (let use=0;use<action.uses.max;use++) log.push(ev(createCombatActionUsageEvent(action)));
}
for (const hero of heroes) for (const ability of hero.abilities) log.push(ev({type:'ability-used',abilityId:ability.id}));
for (const [id,item] of Object.entries(replay().inventoryState)) if (id!=='olva-timeout' && item.maxCharges!==null) log.push(ev({type:'item-charge-changed',itemId:id,change:{mode:'set',value:0}}));
log.push(ev({type:'item-changed',itemId:'yellow-snowball',acquired:false}));
log.push(ev({type:'manual-adjustment',label:'Передача',reason:'Тест',adjustment:{kind:'inventory-item',itemId:'buldak-noodles',acquired:true,ownerId:'linda',quantity:1,charges:0}}));
const before = replay();
const command = createOlvaRestCommand(before);
assert.ok(command);
for (const input of [command.charge,command.rest,command.remove,command.used])log.push(ev(input,'full-rest'));
const after = replay();
assert.deepEqual(after.heroHp,after.heroMaxHp);
assert.equal(after.heroHp.linda,41);
assert.ok(!after.participantConditions.linda.includes('downed'));
for (const [id,item] of Object.entries(after.inventoryState)) if(item.maxCharges!==null) assert.equal(item.charges,item.maxCharges,id);
assert.equal(after.inventoryState['buldak-noodles'].ownerId,'linda');
assert.ok(!after.inventory.includes('yellow-snowball'));
assert.ok(!after.inventory.includes('olva-timeout'));
assert.equal(after.resourceUses['linda-ability-pitahaya-summon'],undefined,'Campaign summons also recover');
assert.equal(after.usedAbilities.length,0);
for (const action of allHeroActions) {
  const key=getCombatActionResourceKey(action);
  assert.equal(after.resourceUses[key],undefined,key);
  assert.equal(after.resourceScopes[key],undefined,key);
  const item=after.inventoryState[action.sourceId];
  if(action.source==='ability'||item?.ownerId===action.characterId) assert.ok(isCombatActionSourceAvailable(action,after),action.id);
}
assert.equal(after.resourceUses['linda-ability-magic-whisper'],undefined);
assert.equal(after.resourceUses['linda-item-healing-pollen'],undefined);
assert.ok(isCombatActionSourceAvailable(definition.combatActions.find(a=>a.id==='linda-healing-pollen')!,after),'Restored charges must actually be usable');
assert.equal(createOlvaRestCommand(after),null);
assert.equal(createOlvaRestCommand({...before,combat:{} as NonNullable<typeof before.combat>}),null);
assert.equal(createOlvaRestCommand({...before,flags:{...before.flags,'olva-rest-used':true}}),null);
const expectation={campaignId:definition.campaignId,definitionId:definition.id,definitionVersion:definition.version};
const saved=createStoredGallerySessionEnvelope(log,expectation);
assert.ok(saved);
const parsed=parseStoredGallerySessionEnvelope(JSON.parse(JSON.stringify(saved)),expectation);
assert.ok(parsed.ok);
assert.deepEqual(replayGalleryEvents(parsed.events,definition).inventoryState,after.inventoryState);
assert.deepEqual(replayGalleryEvents(parsed.events,definition).resourceUses,after.resourceUses);
assert.deepEqual(replayGalleryEvents(parsed.events,definition).heroHp,after.heroMaxHp);
log.push(ev({type:'action-corrected',correctedCommandId:'full-rest'}));
assert.deepEqual(replay().heroHp,before.heroHp);
assert.deepEqual(replay().inventoryState,before.inventoryState);
assert.deepEqual(replay().resourceUses,before.resourceUses);
assert.deepEqual(replay().resourceScopes,before.resourceScopes);
assert.deepEqual(replay().usedAbilities,before.usedAbilities);
assert.deepEqual(replay().participantConditions,before.participantConditions);
const ordinary=createSafeLocationRestCommand(before,'hotel-gallery',Object.fromEntries(heroes.map(h=>[h.id,1])));
assert.ok(ordinary);
const oldRest=replayGalleryEvents([seed, ...log.slice(1,-5), ev(ordinary)],definition);
assert.equal(oldRest.heroHp.bubsilda,1,'Historical ordinary rest remains d8');
assert.equal(oldRest.inventoryState['healing-pollen'].charges,0,'Ordinary rest does not refill campaign items');
console.log('PASS: full HP, downed recovery, current max HP, all item charges and actual usability, ownership, ALL ability/item scopes including campaign, one-use guard, legacy d8, persistence and atomic undo.');
